src/ALU.sv
src/branch_unit.sv
src/commit_stage.sv
src/core.sv
src/data_mem.sv
src/execute_stage.sv
src/inst_mem.sv
src/instr_decoder.sv
src/issue_stage.sv
src/mem_wrap.sv
src/mul_div.sv
src/regfile.sv
src/scoreboard_data_hazards.sv
src/frontend_stage.sv
src/decode_stage.sv
src/csr.sv
src/csr_regfile.sv
uvm/pkg_memory.sv
uvm/pkg_main.sv
uvm/core_if.sv
uvm/reg_if.sv
uvm/wrapper.sv
uvm/top.sv
+incdir+./uvm
+incdir+